url: https://evandrofilho.github.io
baseurl: /Meeps/

# Site settings
title: Meeps
email: epbf.snf17@uea.edu.br
description: "Seja bem vindo ao Meeps"


# Team names, titles and social links
people:
- name: Evandro Filho
  pic: 1
  position: Líder

- name: Paulo Roberto
  pic: 2
  position: Programador

- name: Edson Ferreira 
  pic: 3
  position: Programador

- name: Michael Henrique
  pic: 4
  position: Programador


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/EvandroFilho/Meeps

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
